#!/bin/sh
set -eu
cd "$(dirname "$0")/.."
if [ "${1:-}" != "--skip-build" ]; then ./mvnw -B -ntp verify; fi
mkdir -p target/lab-runs
lab_run=$(mktemp -d "$PWD/target/lab-runs/run-XXXXXX")
java lab/Prepare.java "$lab_run"
# Configuration is generated by Java to escape paths correctly on every platform.
java scripts/WriteLabConfig.java "$PWD/target/synthetic-maven-cache" "$lab_run/config.local.json"
java -jar target/maven-legacy-analyzer.jar scan "$lab_run/projects" --config "$lab_run/config.local.json" --output "$lab_run/report"
java --class-path target/maven-legacy-analyzer.jar lab/Verify.java "$lab_run/report/analysis.json"
printf 'Report: %s/report/index.html\n' "$lab_run"
